name: Push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/Dockerfile'

env:
  IMAGE_NAME: ubuntu-runner


jobs:
  build:
    timeout-minutes: 60
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker buildX
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.YANDEX_USER }}
          password: ${{ secrets.YANDEX_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha, event=branch
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          pull: true
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,mode=max,ref=${{ secrets.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}:cache,oci-mediatypes=true,image-manifest=true
